linkedin/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('linkedinapp.urls')),  

]

linkedinapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .admin import ClientAdmin


urlpatterns = [
    path('home/', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),  # Logout URL
    path('client/dashboard/', views.client_dashboard, name='client_dashboard'),
    path('freelancer/dashboard/', views.freelancer_dashboard, name='freelancer_dashboard'),
    path('signup/', views.signup_view, name='signup'),
    path('successsignup/', views.signup_view, name='signup'),
    path('create_project/', views.create_project, name='create_project'),
    path('project_dashboard/<int:project_id>/', views.project_dashboard, name='project_dashboard'),
    path('create_jobpost/<int:project_id>/', views.create_jobpost, name='create_jobpost'),
    path('create_jobproposal/<int:jobpost_id>/', views.create_jobproposal, name='create_jobproposal'),
    path('freelancer/jobproposals/<int:jobpost_id>/', views.job_proposal_list, name='job_proposal_list'),
    path('job_proposal_list/<int:jobpost_id>/', views.job_proposal_list, name='job_proposal_list'),
    path('accept_proposal/<int:proposal_id>/', views.accept_proposal, name='accept_proposal'),
    path('account_verification/', views.account_verification, name='account_verification'),
        path('verify_clients/<int:pk>/', views.verify_clients, name='verify_clients'),





]

linkedinapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)
    is_verified = models.BooleanField(default=False)


    def __str__(self):
        return self.name


class Freelancer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Project(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name


class JobPost(models.Model):
    JOB_STATUS_CHOICES = (
        ('ACTIVE', 'Active'),
        ('INACTIVE', 'Inactive'),
        ('COMPLETED', 'Completed'),
    )

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    description = models.TextField()
    hourly_rate = models.CharField(max_length=10)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    status = models.CharField(max_length=10, choices=JOB_STATUS_CHOICES, default='ACTIVE')

    def __str__(self):
        return f'{self.project.name} - {self.description}'

class JobProposal(models.Model):
    PROPOSAL_CHOICES = (
        ('OPEN', 'Open'),
        ('ENGAGED', 'Engaged'),
        ('REJECTED', 'Rejected'),
    )

    job_post = models.ForeignKey(JobPost, on_delete=models.CASCADE)
    freelancer = models.ForeignKey(Freelancer, on_delete=models.CASCADE)
    freelancer_hourly_rate = models.CharField(max_length=10)
    proposal_status = models.CharField(max_length=10, choices=PROPOSAL_CHOICES, default='OPEN')

    def __str__(self):
        return f"{self.freelancer} - {self.proposal_status}"

linkedinapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.db import models
from .models import Client, Freelancer, Project , JobPost , JobProposal
from django.contrib.auth import authenticate, login , logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .permissions import client_required, freelancer_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect




# Create your views here.
def home(request):
    return render(request, 'home.html')

def logout_view(request):
    logout(request)
    return redirect('home')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if Client.objects.filter(user=user).exists():
                login(request, user)
                return redirect('client_dashboard')
            elif Freelancer.objects.filter(user=user).exists():
                login(request, user)
                return redirect('freelancer_dashboard')

        messages.error(request, 'Invalid username or password.')

    return render(request, 'login.html')

def account_verification(request):
    return render(request, 'account_verification.html')

@client_required
def client_dashboard(request):
    if hasattr(request.user, 'client'):
        client = request.user.client
        if client.is_verified:
            projects = Project.objects.filter(client=client)
            return render(request, 'client_dashboard.html', {'projects': projects})
        else:
            return render(request, 'account_verification.html')
    else:
        return redirect('home')

@client_required
def project_dashboard(request, project_id):
    if hasattr(request.user, 'client'):
        # project = Project.objects.get(Project, id=project_id, client__user=request.user)
        project = Project.objects.get(id=project_id, client__user=request.user)

        job_proposals = JobProposal.objects.filter(job_post__project=project)
        return render(request, 'project_dashboard.html', {'project': project, 'job_proposals': job_proposals})
    else:
        return redirect('home')

@client_required
def create_project(request):
    if hasattr(request.user, 'client'):
        if request.method == 'POST':
            project_name = request.POST['project_name']
            
            # Get the current user as the client
            client = request.user.client
    
            # Create a new Project object
            project = Project.objects.create(client=client, name=project_name)
    
            # Redirect to the client dashboard 
            return redirect('client_dashboard')
    
        return render(request, 'create_project.html')
    else:
        return redirect('home')


@client_required
def create_jobpost(request, project_id):
    if hasattr(request.user, 'client'):
        project = Project.objects.get(id=project_id, client__user=request.user)
        
        if request.method == 'POST':
            # Retrieve form data and create a new JobPost object
            description = request.POST['description']
            hourly_rate = request.POST['hourly_rate']
            start_date = request.POST['start_date']
            end_date = request.POST['end_date']
            status = request.POST['status']
            job_post = JobPost.objects.create(project=project, description=description, hourly_rate=hourly_rate, start_date=start_date, end_date=end_date, status=status)
            
            # Redirect to the project dashboard
            return redirect('project_dashboard', project_id=project_id)

        return render(request, 'create_jobpost.html', {'project': project})
    else:
        return redirect('home')


@freelancer_required
def freelancer_dashboard(request):
    if hasattr(request.user, 'freelancer'):
        # Retrieve all the job posts
        job_posts = JobPost.objects.all()
        return render(request, 'freelancer_dashboard.html', {'job_posts': job_posts})
    else:
        return redirect('home')
    
def signup_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        signup_user = request.POST['signup_user']

        # Create a new User object
        user = User.objects.create_user(username=username, password=password)

        if signup_user == 'client':
            # Create a new Client object and link it to the User object
            client = Client.objects.create(user=user, name=username)
        elif signup_user == 'freelancer':
            # Create a new Freelancer object and link it to the User object
            freelancer = Freelancer.objects.create(user=user, name=username)

        return render(request, 'success_signup.html')

    return render(request, 'signup.html')

@freelancer_required
def create_jobproposal(request, jobpost_id):
    if request.method == 'POST':
        # Retrieve form data and create a new JobProposal object
        job_post = JobPost.objects.get(id=jobpost_id)
        freelancer = Freelancer.objects.get(user=request.user)
        freelancer_hourly_rate = request.POST['freelancer_hourly_rate']
        proposal_status = 'OPEN'  # Set the initial status as 'OPEN'
        
        job_proposal = JobProposal.objects.create(job_post=job_post, freelancer=freelancer, freelancer_hourly_rate=freelancer_hourly_rate, proposal_status=proposal_status)
        
        return redirect('freelancer_dashboard')

    # If the request method is GET, retrieve the job post object and render the create_jobproposal.html template
    job_post = JobPost.objects.get(id=jobpost_id)
    return render(request, 'create_jobproposal.html', {'job_post': job_post})


# @freelancer_required
@client_required
def job_proposal_list(request, jobpost_id):
    
    # Retrieve the job proposals for the specific job post
    job_proposals = JobProposal.objects.filter(job_post_id=jobpost_id)

    context = {
        'job_proposals': job_proposals,
    }
    return render(request, 'job_proposal_list.html', context)


@login_required(login_url='login')
def accept_proposal(request, proposal_id):
    proposal = JobProposal.objects.get(id=proposal_id)

    if proposal.proposal_status == 'OPEN':
        proposal.proposal_status = 'ACCEPTED'
        proposal.save()

        # Reject all other proposals for the same job post
        other_proposals = JobProposal.objects.filter(job_post=proposal.job_post).exclude(id=proposal_id)
        for other_proposal in other_proposals:
            other_proposal.proposal_status = 'REJECTED'
            other_proposal.save()

    return redirect('job_proposal_list', jobpost_id=proposal.job_post.id)

def verify_clients(request, pk):
    client = get_object_or_404(Client, pk=pk)
    client.is_verified = True
    client.save()
    return HttpResponseRedirect(reverse('admin:linkedinapp_client_changelist'))

linkedinapp/templates/account_verification.html
<h1>Hello, {{ request.user.username }}!</h1>
<h2> congratulations,you have created an Client's account successfully </h2>
<h4>Your account is under verification. Please wait for the next 24 hours to be verified</h4>

linkedinapp/templates/client_dashboard.html
<h2>Welcome to the Client Dashboard</h2>
{% comment %} <p>Hello, {{ request.user.username }}!</p> {% endcomment %}
<h1>Welcome, {{ request.user.username }}</h1>

<h3>Your Projects:</h3>
<ul>
  {% for project in projects %}
    <li>
      <a href="{% url 'project_dashboard' project.id %}">
        <strong></strong> {{ project.name }}
      </a>
    </li>
  {% empty %}
    <li>No projects available.</li>
  {% endfor %}
</ul>

<h3>Create Project:</h3>
<a href="{% url 'create_project' %}" class="btn btn-primary">Create Project</a><br>

<a href="{% url 'logout' %}">Logout</a>

linkedinapp/templates/create_jobpost.html
<form method="POST" action="{% url 'create_jobpost' project.id %}">
  {% csrf_token %}
  <div class="form-group">
    <label for="description">Description:</label>
    <textarea class="form-control" id="description" name="description" rows="2" required></textarea>
  </div>
  <div class="form-group">
    <label for="hourly_rate">Hourly Rate:</label>
    <input type="text" class="form-control" id="hourly_rate" name="hourly_rate" required>
  </div>
  <div class="form-group">
    <label for="start_date">Start Date:</label>
    <input type="date" class="form-control" id="start_date" name="start_date" required>
  </div>
  <div class="form-group">
    <label for="end_date">End Date:</label>
    <input type="date" class="form-control" id="end_date" name="end_date" required>
  </div>
  <div class="form-group">
    <label for="status">Status:</label>
    <select class="form-control" id="status" name="status" required>
      <option value="ACTIVE">Active</option>
      <option value="INACTIVE">Inactive</option>
      <option value="INACTIVE">Completed</option>
    </select>
  </div>
  <button type="submit" class="btn btn-primary">Create Job Post</button>
</form>

linkedinapp/templates/create_jobproposal.html
<form method="POST" action="{% url 'create_jobproposal' job_post.id %}">
  {% csrf_token %}
  <div class="form-group">
    <label for="freelancer_hourly_rate">Hourly Rate:</label>
    <input type="text" class="form-control" id="freelancer_hourly_rate" name="freelancer_hourly_rate" required>
  </div>
  <button type="submit" class="btn btn-primary">Submit Proposal</button>
</form>

linkedinapp/templates/create_project.html
<h3>Create Project</h3>
<form method="POST" action="{% url 'create_project' %}">
  {% csrf_token %}
  
  <label for="project_name">Project Name:</label>
  <input type="text" id="project_name" name="project_name" required><br>
  
  <input type="submit" value="Save Project">
</form>

linkedinapp/templates/freelancer_dashboard.html
<<h2>Welcome to the freelancer Dashboard</h2><br>
<a href="{% url 'logout' %}">Logout</a>

<p>Hello, {{ request.user.username }}!</p>
{% comment %} <h1>hello, {{ freelancer.name }}</h1> {% endcomment %}

<div class="d-grid gap-2 d-md-flex justify-content-md-end">
  {% comment %} <a href="{% url 'job_proposal_list' jobpost_id=job_post.id %}" class="btn btn-primary me-md-2">See Your Job Proposals</a> {% endcomment %}
</div>

<h2>All the job posts are here</h2>

{% for job_post in job_posts %}
  <div class="job-post">
    <h3>{{ job_post.project.name }}</h3>
    <p>{{ job_post.description }}</p>
    <p>Hourly Rate: {{ job_post.hourly_rate }}</p>
    <p>Status: {{ job_post.status }}</p>
    <a href="{% url 'create_jobproposal' jobpost_id=job_post.id %}" class="btn btn-primary">Apply</a>
  </div>
{% empty %}
  <p>No job posts available.</p>
{% endfor %}

linkedinapp/templates/home.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Signup</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

linkedinapp/templates/job_proposal_list.html
{% comment %} <h2>Job Proposals</h2>

{% if job_proposals %}
  <table>
    <tr>
      <th>Freelancer Name</th>
      <th>Hourly Rate</th>
      <th>Status</th>
    </tr>
    {% for proposal in job_proposals %}
      <tr>
        <td>{{ proposal.freelancer.user.username }}</td>
        <td>{{ proposal.freelancer_hourly_rate }}</td>
        <td>{{ proposal.get_proposal_status_display }}</td>
      </tr>
    {% endfor %}
  </table>
{% else %}
  <p>No job proposals available for this job post.</p>
{% endif %} {% endcomment %}

<h2>Job Proposals</h2>

{% if job_proposals %}
  <table>
    <tr>
      <th>Freelancer Name</th>
      <th>Hourly Rate</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
    {% for proposal in job_proposals %}
      <tr>
        <td>{{ proposal.freelancer.user.username }}</td>
        <td>{{ proposal.freelancer_hourly_rate }}</td>
        <td>{{ proposal.get_proposal_status_display }}</td>
        <td>
          {% if proposal.proposal_status == 'OPEN' %}
            <form method="POST" action="{% url 'accept_proposal' proposal.id %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">Accept</button>
            </form>
          {% else %}
            
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </table>
{% else %}
  <p>No job proposals available for this job post.</p>
{% endif %}

linkedinapp/templates/login.html
<h2>Login</h2>
<form method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required><br>
    <input type="submit" value="Login">
</form>

linkedinapp/templates/project_dashboard.html
{% comment %} <h2>Project Dashboard</h2>
<p>Project Name: {{ project.name }}</p>

<h3>Create Job Post:</h3>
<a href="{% url 'create_jobpost' project.id %}" class="btn btn-primary">Create Job Post</a>

<h3>Job Posts:</h3>
{% if project.jobpost_set.all %}
  <ul>
    {% for jobpost in project.jobpost_set.all %}
      <li>
        <strong>Description:</strong>
        <a href="{% url 'job_proposal_list' jobpost.id %}">{{ jobpost.description }}</a><br>
        <strong>Hourly Rate:</strong> {{ jobpost.hourly_rate }} <br>
        <strong>Start Date:</strong> {{ jobpost.start_date }} <br>
        <strong>End Date:</strong> {{ jobpost.end_date }}<br>
        <strong>Status:</strong> {{ jobpost.status }}
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No job posts found for this project.</p>
{% endif %} {% endcomment %}

<h2>Project Dashboard</h2>
<p>Project Name: {{ project.name }}</p>

<h3>Create Job Post:</h3>
<a href="{% url 'create_jobpost' project.id %}" class="btn btn-primary">Create Job Post</a>

<h3>Job Posts:</h3>
{% if project.jobpost_set.all %}
  <ul>
    {% for jobpost in project.jobpost_set.all %}
      <li>
        <strong>Description:</strong>
        <a href="{% url 'job_proposal_list' jobpost.id %}">{{ jobpost.description }}</a><br>
        <strong>Hourly Rate:</strong> {{ jobpost.hourly_rate }} <br>
        <strong>Start Date:</strong> {{ jobpost.start_date }} <br>
        <strong>End Date:</strong> {{ jobpost.end_date }}<br>
        <strong>Status:</strong> {{ jobpost.status }}<br>
        <strong>Freelancer Name:</strong> {{ jobpost.freelancer.name }}
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>No job posts found for this project.</p>
{% endif %}

linkedinapp/templates/signup.html
<h2>Signup</h2>
<form method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required><br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required><br>
    <label for="signup_user">Signup as:</label>
    <select id="signup_user" name="signup_user" required>
        <option value="client">Client</option>
        <option value="freelancer">Freelancer</option>
    </select><br>
    <input type="submit" value="Signup">
</form>

linkedinapp/templates/success_signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Signup Success</title>
</head>
<body>
    <h1>Signup Successful!</h1>
    <p>Congratulations! Your signup process was successful.</p>
</body>
</html>